# Services for Smart Appliance Monitor

start_cycle:
  name: Start cycle manually
  description: Forces the start of a monitoring cycle to test the system.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

stop_monitoring:
  name: Stop monitoring
  description: Temporarily stops monitoring the appliance.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

reset_statistics:
  name: Reset statistics
  description: Resets all statistics (last cycle, daily, monthly).
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

generate_dashboard_yaml:
  name: Generate dashboard YAML
  description: Generates optimized dashboard YAML code for this appliance. The YAML is displayed in a notification and logged.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor
    use_custom_cards:
      name: Use custom cards
      description: Include custom cards (mushroom, mini-graph-card) in the template. Requires HACS and card installation.
      default: true
      selector:
        boolean:

export_to_csv:
  name: Export to CSV
  description: Exports appliance data to CSV format. The CSV content is returned and optionally saved to a file.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor
    file_path:
      name: File path
      description: Optional path where to save the CSV file (e.g., /config/exports/washing_machine.csv)
      required: false
      selector:
        text:

export_to_json:
  name: Export to JSON
  description: Exports appliance data to JSON format. The JSON content is returned and optionally saved to a file.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor
    file_path:
      name: File path
      description: Optional path where to save the JSON file (e.g., /config/exports/washing_machine.json)
      required: false
      selector:
        text:

force_shutdown:
  name: Force shutdown
  description: Manually triggers the auto-shutdown for testing purposes. Only works if auto-shutdown is enabled and configured.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

sync_with_energy_dashboard:
  name: Sync with Energy Dashboard
  description: Checks synchronization status between Smart Appliance Monitor devices and Home Assistant Energy Dashboard. Generates a detailed report with synced devices, missing devices, and recommendations.
  fields:
    entity_id:
      name: Entity (optional)
      description: Specific appliance entity to sync. If not provided, syncs all SAM devices.
      required: false
      selector:
        entity:
          integration: smart_appliance_monitor
          domain: sensor

export_energy_config:
  name: Export Energy Dashboard Config
  description: Exports the Energy Dashboard configuration for a specific appliance. Provides JSON configuration and step-by-step instructions to add the device to Energy Dashboard.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

get_energy_data:
  name: Get Energy Data
  description: Retrieves aggregated energy data for SAM devices. Returns energy consumption, costs, and device breakdown for a specified period. Fires an event with the data for custom dashboards.
  fields:
    period_start:
      name: Period Start
      description: Start of the period (ISO format, e.g., "2025-10-21T00:00:00"). Defaults to today at midnight.
      required: false
      selector:
        text:
    period_end:
      name: Period End
      description: End of the period (ISO format, e.g., "2025-10-21T23:59:59"). Defaults to now.
      required: false
      selector:
        text:
    devices:
      name: Devices
      description: Optional list of device names to include. If not provided, includes all SAM devices.
      required: false
      advanced: true
      selector:
        object:
