# Services for Smart Appliance Monitor

start_cycle:
  name: Start cycle manually
  description: Forces the start of a monitoring cycle to test the system.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

stop_monitoring:
  name: Stop monitoring
  description: Temporarily stops monitoring the appliance.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

reset_statistics:
  name: Reset statistics
  description: Resets all statistics (last cycle, daily, monthly).
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

generate_dashboard_yaml:
  name: Generate dashboard YAML
  description: Generates optimized dashboard YAML code for this appliance. The YAML is displayed in a notification and logged.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor
    use_custom_cards:
      name: Use custom cards
      description: Include custom cards (mushroom, mini-graph-card) in the template. Requires HACS and card installation.
      default: true
      selector:
        boolean:

export_to_csv:
  name: Export to CSV
  description: Exports appliance data to CSV format. The CSV content is returned and optionally saved to a file.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor
    file_path:
      name: File path
      description: Optional path where to save the CSV file (e.g., /config/exports/washing_machine.csv)
      required: false
      selector:
        text:

export_to_json:
  name: Export to JSON
  description: Exports appliance data to JSON format. The JSON content is returned and optionally saved to a file.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor
    file_path:
      name: File path
      description: Optional path where to save the JSON file (e.g., /config/exports/washing_machine.json)
      required: false
      selector:
        text:

force_shutdown:
  name: Force shutdown
  description: Manually triggers the auto-shutdown for testing purposes. Only works if auto-shutdown is enabled and configured.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor
