# Services for Smart Appliance Monitor

start_cycle:
  name: Start cycle manually
  description: Forces the start of a monitoring cycle to test the system.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

stop_monitoring:
  name: Stop monitoring
  description: Temporarily stops monitoring the appliance.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

reset_statistics:
  name: Reset statistics
  description: Resets all statistics (last cycle, daily, monthly).
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

generate_dashboard_yaml:
  name: Generate dashboard YAML
  description: Generates optimized dashboard YAML code for this appliance. The YAML is displayed in a notification and logged.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor
    use_custom_cards:
      name: Use custom cards
      description: Include custom cards (mushroom, mini-graph-card) in the template. Requires HACS and card installation.
      default: true
      selector:
        boolean:
