# Services for Smart Appliance Monitor

start_cycle:
  name: Start cycle manually
  description: Forces the start of a monitoring cycle to test the system.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

stop_monitoring:
  name: Stop monitoring
  description: Temporarily stops monitoring the appliance.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

reset_statistics:
  name: Reset statistics
  description: Resets all statistics (last cycle, daily, monthly).
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

generate_dashboard_yaml:
  name: Generate dashboard YAML
  description: Generates optimized dashboard YAML code for this appliance. The YAML is displayed in a notification and logged.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor
    use_custom_cards:
      name: Use custom cards
      description: Include custom cards (mushroom, mini-graph-card) in the template. Requires HACS and card installation.
      default: true
      selector:
        boolean:

export_to_csv:
  name: Export to CSV
  description: Exports appliance data to CSV format. The CSV content is returned and optionally saved to a file.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor
    file_path:
      name: File path
      description: Optional path where to save the CSV file (e.g., /config/exports/washing_machine.csv)
      required: false
      selector:
        text:

export_to_json:
  name: Export to JSON
  description: Exports appliance data to JSON format. The JSON content is returned and optionally saved to a file.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor
    file_path:
      name: File path
      description: Optional path where to save the JSON file (e.g., /config/exports/washing_machine.json)
      required: false
      selector:
        text:

force_shutdown:
  name: Force shutdown
  description: Manually triggers the auto-shutdown for testing purposes. Only works if auto-shutdown is enabled and configured.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

sync_with_energy_dashboard:
  name: Sync with Energy Dashboard
  description: Checks synchronization status between Smart Appliance Monitor devices and Home Assistant Energy Dashboard. Generates a detailed report with synced devices, missing devices, and recommendations.
  fields:
    entity_id:
      name: Entity (optional)
      description: Specific appliance entity to sync. If not provided, syncs all SAM devices.
      required: false
      selector:
        entity:
          integration: smart_appliance_monitor
          domain: sensor

export_energy_config:
  name: Export Energy Dashboard Config
  description: Exports the Energy Dashboard configuration for a specific appliance. Provides JSON configuration and step-by-step instructions to add the device to Energy Dashboard.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor

get_energy_data:
  name: Get Energy Data
  description: Retrieves aggregated energy data for SAM devices. Returns energy consumption, costs, and device breakdown for a specified period. Fires an event with the data for custom dashboards.
  fields:
    period_start:
      name: Period Start
      description: Start of the period (ISO format, e.g., "2025-10-21T00:00:00"). Defaults to today at midnight.
      required: false
      selector:
        text:
    period_end:
      name: Period End
      description: End of the period (ISO format, e.g., "2025-10-21T23:59:59"). Defaults to now.
      required: false
      selector:
        text:
    devices:
      name: Devices
      description: Optional list of device names to include. If not provided, includes all SAM devices.
      required: false
      advanced: true
      selector:
        object:

analyze_cycles:
  name: Analyze Cycles with AI
  description: Analyzes appliance usage cycles using AI to provide insights, recommendations, and optimization opportunities. Requires AI Task entity to be configured in global settings.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity to analyze
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor
    analysis_type:
      name: Analysis Type
      description: Type of AI analysis to perform
      default: all
      selector:
        select:
          options:
            - label: All Analysis Types
              value: all
            - label: Pattern Analysis
              value: pattern
            - label: Recommendations
              value: recommendations
    cycle_count:
      name: Cycle Count
      description: Number of historical cycles to analyze (1-50)
      default: 10
      selector:
        number:
          min: 1
          max: 50
          mode: box
    export_format:
      name: Export Format
      description: Format for data export if save_export is enabled
      default: json
      advanced: true
      selector:
        select:
          options:
            - json
            - csv
            - both
    save_export:
      name: Save Export
      description: Save exported data to files in /config directory
      default: false
      advanced: true
      selector:
        boolean:

analyze_energy_dashboard:
  name: Analyze Energy Dashboard with AI
  description: Performs AI analysis on overall home energy consumption using Energy Dashboard data. Provides global recommendations and efficiency scoring. Requires AI Task entity to be configured in global settings.
  fields:
    period:
      name: Analysis Period
      description: Time period to analyze
      default: today
      selector:
        select:
          options:
            - label: Today
              value: today
            - label: Yesterday
              value: yesterday
            - label: Last 7 Days
              value: week
            - label: This Month
              value: month
    compare_previous:
      name: Compare with Previous Period
      description: Include comparison with the previous period (yesterday, last week, last month)
      default: false
      selector:
        boolean:
    include_recommendations:
      name: Include Recommendations
      description: Include detailed recommendations in the analysis
      default: true
      advanced: true
      selector:
        boolean:

set_global_config:
  name: Set Global Configuration
  description: Configure global AI analysis and pricing settings for all appliances. Replaces configure_ai service.
  fields:
    ai_task_entity:
      name: AI Task Entity
      description: Entity ID of the AI Task to use for analysis (e.g., ai_task.openai_ai_task)
      required: false
      example: "ai_task.openai_ai_task"
      selector:
        entity:
          domain: ai_task
    global_price_entity:
      name: Global Price Entity
      description: Entity providing electricity price for all appliances
      required: false
      example: "sensor.electricity_price"
      selector:
        entity:
          domain:
            - sensor
            - input_number
    global_price_fixed:
      name: Fixed Price per kWh
      description: Fixed price per kWh (fallback if no entity configured)
      required: false
      example: 0.2516
      selector:
        number:
          min: 0
          max: 10
          step: 0.001
          unit_of_measurement: "€/kWh"
    enable_ai_analysis:
      name: Enable AI Analysis
      description: Enable or disable AI analysis globally
      required: false
      selector:
        boolean:
    ai_analysis_trigger:
      name: Analysis Trigger
      description: When to automatically trigger AI analysis
      required: false
      selector:
        select:
          options:
            - label: Manual (Via Service Only)
              value: manual
            - label: Automatic (After Each Cycle)
              value: auto_cycle_end
            - label: Periodic (Daily)
              value: periodic_daily
            - label: Periodic (Weekly)
              value: periodic_weekly

detect_tariff_system:
  name: Detect Tariff System
  description: Analyze electricity price history to detect peak/off-peak tariff structure (e.g., heures creuses/pleines). Requires a price entity to be configured.
  fields: {}

configure_ai:
  name: "[DEPRECATED] Configure AI Analysis"
  description: "DEPRECATED: Use set_global_config instead. This service will be removed in a future version."
  fields:
    ai_task_entity:
      name: AI Task Entity
      description: Entity ID of the AI Task to use for analysis
      required: false
      example: "ai_task.openai_ai_task"
      selector:
        entity:
          domain: ai_task
    global_price_entity:
      name: Global Price Entity
      description: Default electricity price entity for all appliances
      required: false
      example: "input_number.electricity_price"
      selector:
        entity:
          domain:
            - input_number
            - sensor
    enable_ai_analysis:
      name: Enable AI Analysis
      description: Enable or disable AI analysis globally
      required: false
      selector:
        boolean:
    ai_analysis_trigger:
      name: Analysis Trigger
      description: When to automatically trigger AI analysis
      required: false
      selector:
        select:
          options:
            - label: Automatic (After Each Cycle)
              value: auto_cycle_end
            - label: Manual (Via Service Only)
              value: manual
            - label: Periodic (Daily)
              value: periodic_daily
            - label: Periodic (Weekly)
              value: periodic_weekly

get_cycle_history:
  name: Get Cycle History
  description: Retrieves cycle history from Recorder with optional filters. Returns cycles and statistics for the specified period.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor
    period_start:
      name: Period Start
      description: Start of the period (ISO format, e.g., "2025-09-01T00:00:00"). Defaults to 30 days ago.
      required: false
      example: "2025-09-01T00:00:00"
      selector:
        text:
    period_end:
      name: Period End
      description: End of the period (ISO format, e.g., "2025-10-22T23:59:59"). Defaults to now.
      required: false
      example: "2025-10-22T23:59:59"
      selector:
        text:
    min_duration:
      name: Minimum Duration
      description: Minimum cycle duration in minutes
      required: false
      advanced: true
      selector:
        number:
          min: 0
          max: 1440
          mode: box
          unit_of_measurement: "min"
    max_duration:
      name: Maximum Duration
      description: Maximum cycle duration in minutes
      required: false
      advanced: true
      selector:
        number:
          min: 0
          max: 1440
          mode: box
          unit_of_measurement: "min"
    min_energy:
      name: Minimum Energy
      description: Minimum energy consumption in kWh
      required: false
      advanced: true
      selector:
        number:
          min: 0
          max: 100
          step: 0.1
          mode: box
          unit_of_measurement: "kWh"
    max_energy:
      name: Maximum Energy
      description: Maximum energy consumption in kWh
      required: false
      advanced: true
      selector:
        number:
          min: 0
          max: 100
          step: 0.1
          mode: box
          unit_of_measurement: "kWh"
    limit:
      name: Result Limit
      description: Maximum number of cycles to return
      required: false
      advanced: true
      selector:
        number:
          min: 1
          max: 1000
          mode: box

import_historical_cycles:
  name: Import Historical Cycles
  description: Import historical cycles from power sensor data. Analyzes past data to detect cycles that occurred before the integration was configured. Supports dry-run mode for preview and replace mode to reimport with corrected settings.
  target:
    entity:
      integration: smart_appliance_monitor
      domain: sensor
  fields:
    entity_id:
      name: Entity
      description: The appliance monitor entity
      required: true
      selector:
        entity:
          integration: smart_appliance_monitor
    period_start:
      name: Period Start
      description: Start of the import period (ISO format, e.g., "2025-07-01T00:00:00"). Defaults to 30 days ago.
      required: false
      example: "2025-07-01T00:00:00"
      selector:
        text:
    period_end:
      name: Period End
      description: End of the import period (ISO format, e.g., "2025-10-22T23:59:59"). Defaults to now.
      required: false
      example: "2025-10-22T23:59:59"
      selector:
        text:
    dry_run:
      name: Dry Run (Preview Mode)
      description: If enabled, analyze and show results without saving cycles. Use this to preview what will be imported.
      default: false
      selector:
        boolean:
    replace_existing:
      name: Replace Existing Cycles
      description: >
        If enabled, DELETE all existing cycles in this period for this appliance and import fresh data.
        Useful when changing detection thresholds or correcting data.
        CAUTION: This permanently removes old cycles from the database.
      default: false
      advanced: true
      selector:
        boolean:

generate_dashboard_yaml:
  name: Generate Dashboard YAML
  description: Generates the Smart Appliances dashboard as a YAML file. You must then configure it manually in configuration.yaml (see service response for instructions).
  fields:
    output_path:
      name: Output Path
      description: Custom output path for the YAML file (optional, defaults to config/dashboards/smart-appliances.yaml)
      required: false
      selector:
        text:

configure_dashboard:
  name: Configure Dashboard
  description: Applies personalization settings to the dashboard (colors, visible sections, custom names). After applying configuration, the dashboard is automatically rebuilt.
  fields:
    global_settings:
      name: Global Settings
      description: Global dashboard settings (custom cards, theme, colors, auto-update)
      required: false
      advanced: true
      selector:
        object:
      example:
        use_custom_cards: true
        auto_update: true
        color_scheme:
          primary: "#3498db"
          secondary: "#16a085"
    overview_sections:
      name: Overview Sections
      description: List of sections to show in the overview view (metrics, monitoring, energy_costs, ai_analysis, alerts, energy_management, controls, export)
      required: false
      example:
        - metrics
        - monitoring
        - energy_costs
      selector:
        object:
    appliance_views:
      name: Appliance Views Configuration
      description: Per-appliance view configuration (enabled, template, color, sections visibility)
      required: false
      advanced: true
      example:
        lave_linge:
          enabled: true
          template: washing_machine
          color: "#3498db"
          sections:
            status: true
            statistics: true
            controls: true
      selector:
        object:

toggle_view:
  name: Toggle View
  description: Enables or disables a specific appliance view in the dashboard. When disabled, the tab is removed from the dashboard.
  fields:
    appliance_id:
      name: Appliance ID
      description: ID of the appliance (e.g., lave_linge, lave_vaisselle)
      required: true
      example: "lave_linge"
      selector:
        text:
    enabled:
      name: Enabled
      description: Enable (true) or disable (false) the view
      required: true
      selector:
        boolean:
